apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dirizhor-director
  namespace: monitoring
  labels:
    dirizhor.io/monitoring: pilot
spec:
  namespaceSelector:
    matchNames: [dirizhor-pilot]
  selector:
    matchLabels:
      app.kubernetes.io/name: dirizhor
      app.kubernetes.io/component: director
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: service
          replacement: director
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dirizhor-gateway
  namespace: monitoring
  labels:
    dirizhor.io/monitoring: pilot
spec:
  namespaceSelector:
    matchNames: [dirizhor-pilot]
  selector:
    matchLabels:
      app.kubernetes.io/name: dirizhor
      app.kubernetes.io/component: gateway
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: service
          replacement: gateway
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dirizhor-edge
  namespace: monitoring
  labels:
    dirizhor.io/monitoring: pilot
spec:
  namespaceSelector:
    matchNames: [dirizhor-pilot]
  selector:
    matchLabels:
      app.kubernetes.io/name: dirizhor
      app.kubernetes.io/component: edge
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: service
          replacement: edge
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dirizhor-prometheus-control-plane
  namespace: monitoring
  labels:
    dirizhor.io/monitoring: pilot
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
    - port: http-web
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: service
          replacement: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dirizhor-alertmanager-control-plane
  namespace: monitoring
  labels:
    dirizhor.io/monitoring: pilot
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      operated-alertmanager: "true"
  endpoints:
    - port: http-web
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: service
          replacement: alertmanager
