# syntax=docker/dockerfile:1.7

ARG LLAMA_SERVER_IMAGE
FROM ${LLAMA_SERVER_IMAGE}

ARG MODEL_URL
ADD --checksum=sha256:7485fe6f11af29433bc51cab58009521f205840f5b4ae3a32fa7f92e8534fdf5 \
    --chown=10001:10001 ${MODEL_URL} /models/Qwen3-4B-Q4_K_M.gguf

USER 10001:10001
ENTRYPOINT ["/app/llama-server"]
